# Site settings
title: Sams Miniature Painting
email: samthetutor@samsminiaturepainting.com
description: >
  On my blog, you can really get an insight on
 how to paint models with precision and detail.
 In my videos, I just paint miniatures from 
 the game Imperial Assault, but you
 can use the same techniques that I 
 show to paint any model you want!
 Good luck and have fun!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://samsminiaturepainting.com" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  SamDGoodman

# Build settings
markdown: kramdown
